### ISSUE TITLE
Quotas of rosebud.fund 2.0

### ISSUE THREAD

**Issue by MaxKaay** [0xHabitat/meta#10]
# Bounty
Calculation of Rosebud.fund 2.0
## Scope
- define the new features out of the issues of [rosebud DAO](https://github.com/deora-earth/rosebudDAO/issues)
- calculate efforts to realize features 
- 

## Deliverables
Detailed comments under each issue. See [repo](https://github.com/deora-earth/rosebudDAO/issues)

## Gain for the project
finish work on rosebud.fund 2.0

## Roles
bounty gardener: @MaxKuck / 10 %  
bounty worker: @MaxKuck / 75 %  
bounty reviewer: @johannbarbie  / 15 %

**Comment by johba37** [comment]
i've reviewed the bounty and confirm the quotes in total size of 6.450 DAI.
review steps:
- [x] reviewed all quotes
- [x] pointed out unknown requirements
