### ISSUE TITLE
Implement reputation faucet for DEORA -> DAI exchange

### ISSUE THREAD

**Issue by MaxKaay** [0xHabitat/meta#11]
# Bounty
Implement requirements for reputation policy from issue #9 

## Scope
- find and iterate the best streamlined solution to automate the reputation process
- implement faucet to check the DEORA token reputation balance of the address signing in and allow to burn an amount of DEORA tokens against DAI (max individual payout is limited by the overall percentage of reputation held in the organisation) 
--> i.e. 1.000 DAI are in the profit account of deora --> member logs in with 2.000 DEORA out of 10.000 total (20%) --> member is allowed a maximum burn of 200 DEORA to get 200 DAI (20 % of the 1.000 DAI in profit account) --> he leaves the faucet with 1.800 DEORA left (now only holding 18%) and 200 DAI plus.
- **open question**: this idea benefits short term thinking/behaviour: every time money is in the profit account it make sense to take it out. Otherwise you're not sure when there is going to be money in next time. Saving Deora tokens is a gamble that you will get more money

## Deliverables
- faucet/gnosis safe app 

## Gain for the project
- long-term motivational feature of the DAO + **teal.garden process!**

## Roles
bounty gardener: @MaxKuck / 15%  
bounty worker: @johannbarbie / share  
bounty reviewer: name / share

**Comment by johba37** [comment]
i would make this an 1450 Rep Bounty, because it might take time to get started with gnosis safe apps
