### ISSUE TITLE
budget estimation for rollup MVP

### ISSUE THREAD

**Issue by MaxKaay** [0xHabitat/meta#16]

**Comment by johba37** [comment]
i see the following components:

**MVP scope:**
- rollup - Pinkie said 2 days for the backend. let's make it L + M + M + S = 2350 DAI
  - L - create & deploy rollup
  - M - import moloch contract
  - M - release operator node and test challenges
  - S - change all functions to take [typed data](https://eips.ethereum.org/EIPS/eip-712)
- fronted - @cyan-one can give us an estimate?

**Beyond MVP scope:**
- Setup Wizzard - on mainnet, allow to deploy token and rollup, or bring your own token L + M + S = 1800 DAI
  - L - create wizzard to deploy rollup
  - M - add ability to also deploy custom ERC20 optionally
  - S - fix bugs
- Demo App - provide faucet for demo token and allow user to vote in fictitious DAO. M + S + S
  - M - create test deployment
  - S - write faucet
  - S - adjust styling and fix bugs
- Add colony reputation as input: ~L + M
