### ISSUE TITLE
New pitch presentation with "Habitat 2.0" angle

### ISSUE THREAD

**Issue by MaxKaay** [0xHabitat/meta#20]
# Bounty
updating the existing pitch with our new pivot of L2 govbricks

## Scope
- find useful data of the DeFi space
- deliver problem & solution
- communicate vision and future outcomes of GovBricks
- deliver easy to understand tech insight

## Deliverables
- presentation in gdrive format

## Gain for the project
new external communication

## Roles
bounty gardener: @MaxKuck  / share  
bounty worker: @MaxKuck  / share  
bounty reviewer: name / share

**Comment by ghost** [comment]
"DeFi applications (dapps) are like centralized finance (CeFi) platforms in function, i.e. exchanges, lending markets, savings accounts, etc. Unlike CeFi, however, DeFi platforms are permissionless, like the Bitcoin network.

For example, whereas my son isn’t old enough to open a bank account, he can deposit USD stablecoins in a DeFi app and earn interest, just like a savings account. And I can exchange tokens on Uniswap without having to upload my passport, and justify where I got my funds.

Using DeFi apps requires “connecting” an Ethereum wallet. There’s a growing number of standards for this, including the well-designed Coinbase Wallet for iOS/Android. But the universal standard is the browser-based Metamask wallet, available for Chrome on OS X.

Every interaction you have with a DeFi platform requires a confirmation in your wallet, which maps to a transaction on the Ethereum network, and therefore has a fee associated with it. The fee is dynamically determined, and can get expensive when the Ethereum network is busy."

__
cool summary from here:

https://threadreaderapp.com/thread/1285172000009396224.html

**Comment by ghost** [comment]
https://www.forbes.com/sites/matthougan/2020/07/13/why-ethereum-has-valuethe--opportunity-in-programmable-money--defi/#180436964818
