### ISSUE TITLE
deploy test version of rosebud

### ISSUE THREAD

**Issue by johba37** [0xHabitat/meta#3]
# Bounty

- need a deployment of the DAO to test functionality and UI changes.

## Scope

- deploy contracts
- deploy original contracts, or pokemol

## Deliverables

- working DAO that every-one can test

## Gain for the project

foundation to do UI improvements

## Roles
bounty gardener: @johannbarbie / 10%
bounty worker: @simonweniger @johannbarbie  / 80%
bounty reviewer: @MaxKuck  / 10%

**Comment by MaxKaay** [comment]
reviewer comment: 
added one more issue [#12](https://github.com/deora-earth/rosebudDAO/issues/12)

**Comment by simonweniger** [comment]
this one is done
