### ISSUE TITLE
Guide on howto run a Nutberry/Habitat bode

### ISSUE THREAD

**Issue by IlluminatedUnicorn** [0xHabitat/meta#30]
# Bounty

## Scope
Instruction on how to
- Create a node (on example of raspberry pi)
- Run a node
- Open node to public

## Deliverables
Document with instruction on how to run a habitat node

## Roles
bounty gardener&worker: @eshavkun  / 200
bounty reviewer: @zschavi  / 50

**Comment by ghost** [comment]
done! 

https://github.com/deora-earth/habitat/blob/master/nutberrySetup.md
