### ISSUE TITLE
Workshop with Whiterabbit 

### ISSUE THREAD

**Issue by MaxKaay** [0xHabitat/meta#5]
# Bounty
Prepare and execute workshop for whiterabbit. Focus will be clarification and kick-off of the MolochDAO fork.

## Scope
- Know-how of MolochDAO details, processes and parameters 
- Preparation of workshop materials and information
- hosting and managing the workshop, answering questions and explain the benefits of a DAO

## Deliverables
- workshop preparation materials
- attending and hosting the workshop 

## Gain for the project
new project for our purpose to help organisations coordinate more independently and efficiently.

## Roles
bounty gardener: @MaxKuck  / 50% - 225 DAI
bounty worker: @johannbarbie  / 50% - 225 DAI

**Comment by johba37** [comment]
done and paid out
